### ISSUE TITLE
Remove "Check for Updates" button

### ISSUE THREAD

**Issue by TheBizzle** [Idloj/NetLogo#10]
I think we don't need this button.  We should just check for updates whenever the "Extensions & Include Files" window is opened, I think.

Let me know if you disagree.

**Comment by SethTisue** [comment]
agree

**Comment by Idloj** [comment]
Done.

Should the status be centered like this:
![screenshot from 2018-06-20 15-35-58](https://user-images.githubusercontent.com/8083458/41658644-affe79ac-749f-11e8-9778-51017314cbe7.png)

or aligned to the left like before:
![screenshot from 2018-06-20 15-38-54](https://user-images.githubusercontent.com/8083458/41658821-492d198a-74a0-11e8-8e36-9604d3e08177.png)

?

**Comment by TheBizzle** [comment]
I'd say to leave it on the left and bring the "Update All" button down to where "Check for Updates" used to be.

**Comment by Idloj** [comment]
And would it update all the extensions or all of the libraries (including nls files)?

**Comment by TheBizzle** [comment]
All of the extensions (i.e. all of the things shown in the current tab).
