### ISSUE TITLE
Some extensions (e.g. Pathdir) don't install correctly

### ISSUE THREAD

**Issue by TheBizzle** [Idloj/NetLogo#11]
For example, when I download the Pathdir extension, it shows up in my `extensions` folder as the subfolder `Pathdir-Extension-3.0.3`.  That's because that's the name of the folder inside of the `.zip` file.  The solution to this is to probably make new `.zip`s, which have properly-named folders inside of them.

**Comment by Idloj** [comment]
This is related to us storing the artifacts as we discussed.

**Comment by Idloj** [comment]
I opened NetLogo/NetLogo-Libraries#2 instead.
